import PDFDocument from "pdfkit";

export interface ReportData {
  userName: string;
  fromDate: string;
  toDate: string;
  totalRevenue: number;
  totalExpense: number;
  totalFuel: number;
  totalProfit: number;
  incomeRows: { date: string; category: string; amount: number }[];
  expenseRows: { date: string; type: string; subType: string; amount: number }[];
  fuelRows: { date: string; costInr: number; kmAtFill?: number }[];
}

export const generateReportPdf = (data: ReportData): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const INR = (n: number) =>
      `₹${n.toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

    // ── Header ────────────────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 70).fill("#1a73e8");
    doc.fillColor("white").fontSize(20).text("FleetBook — Monthly Profit Report", 40, 20);
    doc.fontSize(11).text(`${data.fromDate}  →  ${data.toDate}`, 40, 46);
    doc.fillColor("#333").moveDown(3);

    // ── Driver info ───────────────────────────────────────────────────────────
    doc.fontSize(13).text(`Driver: ${data.userName}`, { continued: false });
    doc.moveDown(0.5);

    // ── Summary boxes ─────────────────────────────────────────────────────────
    const boxY = doc.y;
    const boxW = 120;
    const gap = 14;
    const boxes = [
      { label: "Total Revenue", value: INR(data.totalRevenue), color: "#e8f5e9" },
      { label: "Total Expense", value: INR(data.totalExpense), color: "#fce4ec" },
      { label: "Fuel Cost", value: INR(data.totalFuel), color: "#fff3e0" },
      { label: "Net Profit", value: INR(data.totalProfit), color: "#e3f2fd" },
    ];
    boxes.forEach((b, i) => {
      const x = 40 + i * (boxW + gap);
      doc.rect(x, boxY, boxW, 56).fill(b.color);
      doc.fillColor("#555").fontSize(9).text(b.label, x + 8, boxY + 8, { width: boxW - 16 });
      doc.fillColor("#1a73e8").fontSize(13).font("Helvetica-Bold")
        .text(b.value, x + 8, boxY + 24, { width: boxW - 16 });
      doc.font("Helvetica");
    });
    doc.y = boxY + 70;
    doc.fillColor("#333");

    // ── Table helper ──────────────────────────────────────────────────────────
    const drawTable = (
      title: string,
      headers: string[],
      widths: number[],
      rows: string[][]
    ) => {
      doc.moveDown(1);
      doc.fontSize(12).fillColor("#1a73e8").font("Helvetica-Bold").text(title);
      doc.font("Helvetica").fillColor("#333");

      const startX = 40;
      let y = doc.y + 4;

      // header row
      doc.rect(startX, y, widths.reduce((a, b) => a + b, 0), 18).fill("#e8eaf6");
      doc.fillColor("#333").fontSize(9).font("Helvetica-Bold");
      let x = startX;
      headers.forEach((h, i) => {
        doc.text(h, x + 4, y + 4, { width: widths[i] - 8 });
        x += widths[i];
      });
      doc.font("Helvetica");
      y += 18;

      // data rows
      rows.forEach((row, ri) => {
        if (y > doc.page.height - 60) { doc.addPage(); y = 40; }
        if (ri % 2 === 0) doc.rect(startX, y, widths.reduce((a, b) => a + b, 0), 16).fill("#fafafa");
        doc.fillColor("#333").fontSize(8);
        x = startX;
        row.forEach((cell, i) => {
          doc.text(cell, x + 4, y + 3, { width: widths[i] - 8, lineBreak: false });
          x += widths[i];
        });
        y += 16;
      });
      doc.y = y + 4;
    };

    // ── Income table ──────────────────────────────────────────────────────────
    drawTable(
      "Income",
      ["Date", "Category", "Amount"],
      [120, 260, 115],
      data.incomeRows.map((r) => [r.date, r.category, INR(r.amount)])
    );

    // ── Expense table ─────────────────────────────────────────────────────────
    drawTable(
      "Expenses",
      ["Date", "Type", "Sub-Type", "Amount"],
      [100, 130, 130, 115],
      data.expenseRows.map((r) => [r.date, r.type, r.subType, INR(r.amount)])
    );

    // ── Fuel table ────────────────────────────────────────────────────────────
    drawTable(
      "Fuel Records",
      ["Date", "KM at Fill", "Cost"],
      [150, 195, 130],
      data.fuelRows.map((r) => [r.date, String(r.kmAtFill ?? "-"), INR(r.costInr)])
    );

    // ── Footer ────────────────────────────────────────────────────────────────
    doc.moveDown(2);
    doc.fontSize(9).fillColor("#999")
      .text(`Generated by FleetBook on ${new Date().toLocaleString("en-IN")}`, { align: "center" });

    doc.end();
  });
